### ISSUE TITLE
This mod make enemies have item power

### ISSUE THREAD

**Issue by heptaspirit** [BasilPanda/RoR2BaddiesWithItems#1]
version: 1.2.3
issue description:

1. After one stage, some enemies could block my attack and it show effect of **thougher time**.
2. After three or four stage, some enemies ran really fast even faster than me, looks like they have many **goat hoofes**. Some impes ran too fast and warped meanwhile, making it even unbeatable. I also found some lemurian ran too fast to stop...
3. Effect of ukulele apeared in some attack of enemies.

**Comment by BasilPanda** [comment]
Enemy item generation is the point of the mod. I'm not quite sure what the issue is. You can configure the ItemMulitplier setting if its too much for you and/or blacklist certain items that you don't want enemies to have.
