### ISSUE TITLE
When all players are dead it won't show the game over screen and then if all allies are killed the game just has a heart attack.

### ISSUE THREAD

**Issue by MagentaLizard** [BasilPanda/RoR2BaddiesWithItems#10]
mod list: 018d0ebf-f33b-b54a-ec47-c32619096e7d

**Comment by MagentaLizard** [comment]
Also does this work with enemies spawned by the host when using providirector?

**Comment by ghost** [comment]
Please provide a log whenever that happens, as I assume it's what pointed out it was this mod that might have broken things.

As Providirector I have no idea what that mod does or how it works. This mod just subscribes to spawn cards (https://github.com/BasilPanda/RoR2BaddiesWithItems/blob/master/BaddiesWithItems/BaddiesWithItems/SpawnCardSubscription.cs) and checks if the enemy spawned is on a team enemy to the players. Purely server-sided.

**Comment by ghost** [comment]
Tested it for an hour or so, didn't get any errors with the game over screen.
If the game over screen got some sort of "glitched out" and had a white overlay and was uninteractable, that usually happens in multiplayer long runs and with mods, it "just happens" and I've had multiple multiplayer sessions (where this mod wasn't installed) where the screen was locked for a few players but not for others.

**Comment by MagentaLizard** [comment]
I think this was caused by me reviving someone after everyone died
