### ISSUE TITLE
Does not calculate average number of items correctly

### ISSUE THREAD

**Issue by nickelpro** [BasilPanda/RoR2BaddiesWithItems#4]
This is not an average, this is the sum of all items across all players plus the square of the stage number.
https://github.com/BasilPanda/RoR2BaddiesWithItems/blob/312b378b6bb25745d7355e5b4cdd7966b95eddda/BaddiesWithItems/BaddiesWithItems/EnemiesWithItems.cs#L357-L366

**Comment by BasilPanda** [comment]
Thanks!
