### ISSUE TITLE
DivisionByZero-Error

### ISSUE THREAD

**Issue by knigh7m4r3** [BasilPanda/RoR2BaddiesWithItems#8]
Hey,

i recently installed RoR2 again and love this mod in my playthroughs!
But there seems to be a "Bug" caused by an unity-update(?).
My console throws the error-message, which you will see at the end of this post.
I've looked into your code and it seems that the Playercount will not be calculated correctly and therefore be set to zero:
File ItemGeneration.cs -> Line 53 sets _cachedPlayerCount.
                                     -> Line 147 divides by _cachedPlayerCount (which seems to be zero at this time).

I would love to see an update to this mod.

> [Error  : Unity Log] DivideByZeroException: Attempted to divide by zero.
Stack trace:
BaddiesWithItems.ItemGeneration.GenerateItemsToInventory (RoR2.Inventory inventory, RoR2.CharacterMaster masterToCopyFrom) (at <097106c4f0244d438ab2060e3f043257>:IL_0052)
BaddiesWithItems.SpawnCardSubscription.SpawnResultItemAdder (RoR2.SpawnCard+SpawnResult spawnResult) (at <097106c4f0244d438ab2060e3f043257>:IL_007F)
RoR2.SpawnCard.DoSpawn (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, RoR2.DirectorSpawnRequest spawnRequest) (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_0048)
RoR2.DirectorCore.TrySpawnObject (RoR2.DirectorSpawnRequest directorSpawnRequest) (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_0244)
RoR2.CombatDirector.Spawn (RoR2.SpawnCard spawnCard, RoR2.EliteDef eliteDef, UnityEngine.Transform spawnTarget, RoR2.DirectorCore+MonsterSpawnDistance spawnDistance, System.Boolean preventOverhead, System.Single valueMultiplier, RoR2.DirectorPlacementRule+PlacementMode placementMode) (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_00E7)
RoR2.CombatDirector.AttemptSpawnOnTarget (UnityEngine.Transform spawnTarget, RoR2.DirectorPlacementRule+PlacementMode placementMode) (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_021C)
RoR2.CombatDirector.Simulate (System.Single deltaTime) (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_007E)
RoR2.CombatDirector.FixedUpdate () (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_0066)

> [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'UnityEngine.Networking, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:

**Comment by ghost** [comment]
The mod has not been updated for Survivors of the Void yet

**Comment by ghost** [comment]
Forgot to mention that I updated the mod like 2-3 days ago.
Since it's entirely server side, its safe for anybody to download it as long as they are the host, otherwise it does nothing.
