### ISSUE TITLE
Enemies spawn in massive hoards for some reason

### ISSUE THREAD

**Issue by Aardvark04** [BasilPanda/RoR2BaddiesWithItems#9]
After stage 6 enemies spawn in huge hoards for some reason making the game immediately incredibly unfair. This isn't mentioned at all in the mod description and I have no clue what causes it. I restarted the run from the same point with only propersave, this mod and their dependencies however the issue still persisted. Below is an attached video displaying the issue in bulwarks ambry. 

https://user-images.githubusercontent.com/103791623/163652480-4d8be099-3dcf-45a0-a94a-add1ff830423.mp4

**Comment by ghost** [comment]
If you are using the thunderstore version that is outdated and broken.
Use the latest https://github.com/BasilPanda/RoR2BaddiesWithItems/releases/tag/3.0.4
If you are using the latest release, post your mod log

**Comment by ghost** [comment]
Updated the mod for the latest game version
